// <auto-generated />
namespace CodingChallengeGreenSlate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0-preview5-19254-05")]
    public sealed partial class change_layers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_layers));
        
        string IMigrationMetadata.Id
        {
            get { return "201906050701125_change_layers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
